CREATE TABLE tb_pauta
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_tb_pauta PRIMARY KEY (id)
);

CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

CREATE TABLE tb_vote
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    voting_session_id BIGINT                                  NOT NULL,
    vote              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_vote PRIMARY KEY (id)
);

CREATE TABLE tb_voting_session
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    life_time_in_minutes INTEGER                                 NOT NULL,
    start_time           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_open              BOOLEAN                                 NOT NULL,
    pauta_id             BIGINT                                  NOT NULL,
    status               SMALLINT                                NOT NULL,
    CONSTRAINT pk_tb_votingsession PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);

ALTER TABLE tb_vote
    ADD CONSTRAINT FK_TB_VOTE_ON_USER FOREIGN KEY (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_vote
    ADD CONSTRAINT FK_TB_VOTE_ON_VOTINGSESSION FOREIGN KEY (voting_session_id) REFERENCES tb_voting_session (id);

ALTER TABLE tb_voting_session
    ADD CONSTRAINT FK_TB_VOTINGSESSION_ON_PAUTA FOREIGN KEY (pauta_id) REFERENCES tb_pauta (id);